import DashSidebar from "../components/sidebar/DashSidebar";
import "../dashboard.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RegisterLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="flex items center">
          <DashSidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
